

//------------------------------------------------------------------------------
#define cSrcBuffers       5          // Velikost pole pointeru pro odesilani dat
#define cRecBufSize      10          // Velikost bufferu pro prijem dat
#define cLogBufSize     160          // Velikost rotacniho bufferu pro logovani
//------------------------------------------------------------------------------

